# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_file',
            new_name='myfile',
        ),
    ]
