# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20180129_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='myfile',
            new_name='image',
        ),
    ]
