# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20180129_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=uploads.models.profile_image_path),
        ),
    ]
